### ISSUE TITLE
fetchComingSoonLists 这个方法在调用的时候有三个参数 ？{ commit }, page, count 

### ISSUE THREAD

**Issue by yizuierguo** [zhengguorong/maizuo#11]
看了楼主代码，fetchComingSoonLists 这个方法在调用的时候有三个参数 { commit }, page, count 
按道理说 this.$store.dispatch 方法是不支持第三个参数的 所以楼主这里的代码有错误 ，我debug了一下确实是undefined . 类似问题：https://segmentfault.com/q/1010000007185702
`mounted () {
      this.$store.dispatch('fetchComingSoonLists', 1, 10)
    },`
`export const fetchComingSoonLists = ({ commit }, page, count) => {`

**Comment by zhengguorong** [comment]
是的，确实有误
