### ISSUE TITLE
感觉你的项目被抄袭了

### ISSUE THREAD

**Issue by gaoqiang19514** [zhengguorong/maizuo#12]
https://github.com/ChuckCZC/vue-demo-maizuo 这里

**Comment by zhengguorong** [comment]
读书人，不能说抄袭，顶多算模仿吧，哈哈，没关系的

**Comment by gaoqiang19514** [comment]
只是最近挺反感这种行为的，github上越来越多了，把别人的项目copy下来改个名字，就说是自己的，而且我去这个人项目源码看了下，方法名都一样


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：zhengguorong <notifications@github.com>
时间：周三 4月19日 11:42
收件人：zhengguorong/maizuo <maizuo@noreply.github.com>
抄送：gaoqiang19514 <gaoqiang19514@163.com>,Author <author@noreply.github.com>
主题：Re: [zhengguorong/maizuo] 感觉你的项目被抄袭了 (#12)

**Comment by zhengguorong** [comment]
感谢对原创的支持，我也发现有好几个说模仿卖座网了，有一个还上了掘金推荐榜，我感觉那些用了别人源码的，最好在底部有个声明，这是对作者基本的尊重。

**Comment by gaoqiang19514** [comment]
来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：zhengguorong <notifications@github.com>
时间：周三 4月19日 15:30
收件人：zhengguorong/maizuo <maizuo@noreply.github.com>
抄送：gaoqiang19514 <gaoqiang19514@163.com>,Author <author@noreply.github.com>
主题：Re: [zhengguorong/maizuo] 感觉你的项目被抄袭了 (#12)
