### ISSUE TITLE
关于vuex中一个loading问题

### ISSUE THREAD

**Issue by howyhuang** [zhengguorong/maizuo#6]
大神请教下vuexMaizuo2这，你这vuex中app下面配置的一个loading，
然后action里面没有关于loading的，
mutations中又有两个赋值，
App.vue直接调用
computed: mapGetters({
    loading: 'getLoading'
})
看不懂这个getLoading获取了什么值

**Comment by zhengguorong** [comment]
@howyhuang 你看/vuex/modules/film/actions.js这个文件，每当发送ajax请求的时候，我都commit了START_LOADING,就是通过这个action来操作该值的，/vuex/modules/app/mutations.js在这里进行赋值了，getLoading是调用vuex/modules/app/getters.js这里的。
这样的目录结构可能有点晕，他们没有写在同一个模块，第一版的时候是写在一起的，但是后来我发现多人协作的时候，只有一个文件，会经常代码冲突，我就把他都分开了。

**Comment by howyhuang** [comment]
啊谢谢 大神看懂了 哈
