### ISSUE TITLE
关于模拟数据

### ISSUE THREAD

**Issue by zouyifeng** [zhengguorong/maizuo#8]
请教一下demo里面的api链接中的‘’v4‘’是映射到‘’http://m.maizuo.com”域名下吗？提供数据的具体实现方式是怎样的呢？

**Comment by zhengguorong** [comment]
/config/index.js文件下的以下代码，用代理实现    

proxyTable: {
      '/v4': {
        target: 'http://m.maizuo.com',
        changeOrigin: true,
        pathRewrite: {
          '^/v4': '/v4'
        }
      }
    },

**Comment by zouyifeng** [comment]
感谢

**Comment by zhengguorong** [comment]
生产环境的数据。

**Comment by zouyifeng** [comment]
感谢！
